<<<<<<< HEAD
import { useState } from "react";
=======
>>>>>>> e39df6dd3b886c0bc368ae7664462d66544456eb
import "../../styles/hr.css";
import {
  ResponsiveContainer,
  BarChart,
  Bar,
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
} from "recharts";

<<<<<<< HEAD
/* ===== STATIC CHART DATA (OK for now) ===== */
=======
/* ===== CHART DATA ===== */
>>>>>>> e39df6dd3b886c0bc368ae7664462d66544456eb
const reportsByTypeData = [
  { type: "Payroll", count: 8 },
  { type: "Compliance", count: 5 },
  { type: "Analytics", count: 6 },
  { type: "Finance", count: 4 },
];

const reportsTrendData = [
  { month: "Jan", reports: 4 },
  { month: "Feb", reports: 6 },
  { month: "Mar", reports: 9 },
  { month: "Apr", reports: 7 },
];

<<<<<<< HEAD
/* ===== REPORTS SOURCE ===== */
const ALL_REPORTS = [
  {
    name: "Monthly Payroll Summary",
    type: "Payroll",
    period: "Monthly",
    status: "Completed",
  },
  {
    name: "Tax Deduction Report",
    type: "Compliance",
    period: "Financial Year",
    status: "Pending",
  },
  {
    name: "Department Cost Analysis",
    type: "Analytics",
    period: "Quarterly",
    status: "Completed",
  },
];

const Reports = () => {
  /* ===== FILTER STATE ===== */
  const [typeFilter, setTypeFilter] = useState("All");
  const [periodFilter, setPeriodFilter] = useState("All");
  const [statusFilter, setStatusFilter] = useState("All");
  const [search, setSearch] = useState("");

  /* ===== FILTER LOGIC ===== */
  const filteredReports = ALL_REPORTS.filter((r) => {
    const matchType = typeFilter === "All" || r.type === typeFilter;
    const matchPeriod = periodFilter === "All" || r.period === periodFilter;
    const matchStatus = statusFilter === "All" || r.status === statusFilter;
    const matchSearch =
      r.name.toLowerCase().includes(search.toLowerCase());

    return matchType && matchPeriod && matchStatus && matchSearch;
  });

  /* ===== DOWNLOAD HANDLER ===== */
  const downloadReport = (report) => {
    const content = `
Report Name: ${report.name}
Type: ${report.type}
Period: ${report.period}
Status: ${report.status}
Generated By: HR System
`;

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);

    const a = document.createElement("a");
    a.href = url;
    a.download = `${report.name.replace(/\s+/g, "_")}.txt`;
    a.click();

    URL.revokeObjectURL(url);
  };
=======
const Reports = () => {
  const reports = [
    {
      name: "Monthly Payroll Summary",
      type: "Payroll",
      period: "March 2024",
      status: "Completed",
    },
    {
      name: "Tax Deduction Report",
      type: "Compliance",
      period: "FY 2023-24",
      status: "Pending",
    },
    {
      name: "Department Cost Analysis",
      type: "Analytics",
      period: "Q1 2024",
      status: "Completed",
    },
  ];
>>>>>>> e39df6dd3b886c0bc368ae7664462d66544456eb

  return (
    <div className="hr-page">
      {/* PAGE HEADER */}
      <div className="hr-page-header">
        <h2>Reports</h2>
        <p className="hr-subtext">
          View and generate payroll and compliance reports
        </p>
      </div>

<<<<<<< HEAD
      {/* ===== CHARTS ===== */}
      <div className="hr-dashboard-charts reports-charts">
        <div className="hr-card hr-chart-card">
          <h3>Reports by Type</h3>
          <div className="hr-chart-wrapper">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={reportsByTypeData}>
                <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.08)" />
=======
      {/* ===== REPORTS ANALYTICS ===== */}
      <div className="hr-dashboard-charts reports-charts">
        {/* BAR CHART */}
        <div className="hr-card hr-chart-card">
          <h3>Reports by Type</h3>

          <div className="hr-chart-wrapper">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={reportsByTypeData}>
                <CartesianGrid
                  strokeDasharray="3 3"
                  stroke="rgba(255,255,255,0.08)"
                />
>>>>>>> e39df6dd3b886c0bc368ae7664462d66544456eb
                <XAxis dataKey="type" stroke="#9ca3af" />
                <YAxis stroke="#9ca3af" />
                <Tooltip />
                <Bar dataKey="count" fill="#2563eb" radius={[6, 6, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

<<<<<<< HEAD
        <div className="hr-card hr-chart-card">
          <h3>Reports Trend</h3>
          <div className="hr-chart-wrapper">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={reportsTrendData}>
                <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.08)" />
                <XAxis dataKey="month" stroke="#9ca3af" />
                <YAxis stroke="#9ca3af" />
                <Tooltip />
                <Line type="monotone" dataKey="reports" stroke="#22c55e" strokeWidth={3} />
=======
        {/* LINE CHART */}
        <div className="hr-card hr-chart-card">
          <h3>Reports Trend</h3>

          <div className="hr-chart-wrapper">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={reportsTrendData}>
                <CartesianGrid
                  strokeDasharray="3 3"
                  stroke="rgba(255,255,255,0.08)"
                />
                <XAxis dataKey="month" stroke="#9ca3af" />
                <YAxis stroke="#9ca3af" />
                <Tooltip />
                <Line
                  type="monotone"
                  dataKey="reports"
                  stroke="#22c55e"
                  strokeWidth={3}
                  dot={{ r: 4 }}
                />
>>>>>>> e39df6dd3b886c0bc368ae7664462d66544456eb
              </LineChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>

<<<<<<< HEAD
      {/* ===== FILTERS ===== */}
      <div className="hr-reports-filters">
        <div className="hr-filter-group">
          <select
  className="hr-filter"
  value={typeFilter}
  onChange={(e) => setTypeFilter(e.target.value)}
>
  <option value="All">All Types</option>
  <option value="Payroll">Payroll</option>
  <option value="Compliance">Compliance</option>
  <option value="Analytics">Analytics</option>
  <option value="Finance">Finance</option>
</select>

          <select
  className="hr-filter"
  value={periodFilter}
  onChange={(e) => setPeriodFilter(e.target.value)}
>
  <option value="All">All Periods</option>
  <option value="Monthly">Monthly</option>
  <option value="Quarterly">Quarterly</option>
  <option value="Financial Year">Financial Year</option>
</select>


          <select
  className="hr-filter"
  value={statusFilter}
  onChange={(e) => setStatusFilter(e.target.value)}
>
  <option value="All">All Status</option>
  <option value="Completed">Completed</option>
  <option value="Pending">Pending</option>
</select>

=======
      {/* ===== REPORT FILTERS ===== */}
      <div className="hr-reports-filters">
        <div className="hr-filter-group">
          <select className="hr-filter">
            <option>All Types</option>
            <option>Payroll</option>
            <option>Compliance</option>
            <option>Analytics</option>
            <option>Finance</option>
          </select>

          <select className="hr-filter">
            <option>All Periods</option>
            <option>Monthly</option>
            <option>Quarterly</option>
            <option>Financial Year</option>
          </select>

          <select className="hr-filter">
            <option>All Status</option>
            <option>Completed</option>
            <option>Pending</option>
          </select>
>>>>>>> e39df6dd3b886c0bc368ae7664462d66544456eb
        </div>

        <div className="hr-filter-actions">
          <input
            type="text"
            className="hr-filter-search"
            placeholder="Search reports..."
<<<<<<< HEAD
            onChange={(e) => setSearch(e.target.value)}
          />
=======
          />

>>>>>>> e39df6dd3b886c0bc368ae7664462d66544456eb
          <button className="hr-primary-btn">Generate Report</button>
        </div>
      </div>

<<<<<<< HEAD
      {/* ===== TABLE ===== */}
=======
      {/* ===== REPORTS TABLE ===== */}
>>>>>>> e39df6dd3b886c0bc368ae7664462d66544456eb
      <div className="hr-card reports-table">
        <table className="hr-table">
          <thead>
            <tr>
              <th>Report Name</th>
              <th>Type</th>
              <th>Period</th>
              <th>Status</th>
              <th>Action</th>
            </tr>
          </thead>

          <tbody>
<<<<<<< HEAD
            {filteredReports.length === 0 ? (
              <tr>
                <td colSpan="5">No reports found</td>
              </tr>
            ) : (
              filteredReports.map((report, index) => (
                <tr key={index}>
                  <td>{report.name}</td>
                  <td>{report.type}</td>
                  <td>{report.period}</td>
                  <td>
                    <span
                      className={`hr-status ${
                        report.status === "Completed"
                          ? "status-approved"
                          : "status-pending"
                      }`}
                    >
                      {report.status}
                    </span>
                  </td>
                  <td>
                    <button
                      className="hr-download-btn"
                      disabled={report.status === "Pending"}
                      onClick={() => downloadReport(report)}
                    >
                      Download
                    </button>
                  </td>
                </tr>
              ))
            )}
=======
            {reports.map((report, index) => (
              <tr key={index}>
                <td>{report.name}</td>
                <td>{report.type}</td>
                <td>{report.period}</td>
                <td>
                  <span
                    className={`hr-status ${
                      report.status === "Completed"
                        ? "status-approved"
                        : "status-pending"
                    }`}
                  >
                    {report.status}
                  </span>
                </td>
                <td>
                  <button
                    className="hr-download-btn"
                    disabled={report.status === "Pending"}
                  >
                    Download
                  </button>
                </td>
              </tr>
            ))}
>>>>>>> e39df6dd3b886c0bc368ae7664462d66544456eb
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default Reports;
